barebox: update to 2025.06.1/customers/skov/imx6/20260619-1 (v2025.06.1 -> v2025.06.1)
Fix the device tree path of the state node for LAN2's MAC address. It broke in
barebox commit [1] and led to the following error message during boot while
fixing up the kernel devicetree:

  Loading ARM Linux zImage '/mnt/nand0.firmware.ubi.system0//boot/zImage'
  Loading devicetree from '/mnt/nand0.firmware.ubi.system0//boot/imx6dl-skov-revc-lt2.dtb'
  ERROR: skov-imx6 machine: Node /state/ethaddr/eth2 defining the state variable not found.

[1] c00df6a4b552 ("ARM: dts: Fix dtc warnings in state nodes")